### ISSUE TITLE
Return key in cb function

### ISSUE THREAD

**Issue by SnooHD** [codsen/object-merge-advanced#7]
Hello, thanks a ton for creating this amazing package!

I am trying to merge an object with many strings.
Some strings i have to merge like this: `key: 'a'` + `key: 'b'` = `key: 'ab'`
But for other strings i can just return the first value.
I can only differentiate them based on the key.
Is it possible to return `{key: value}` in the callback function instead of only the value?

Thanks,
Mike

**Comment by revelt** [comment]
hi Mike! Thanks for contributing!

> Is it possible to return {key: value} in the callback function instead of only the value?

The algorithm picks a pair of keys, gives you their values in the callback and proposes the result as 3rd argument. You can meddle with that result, but working pair of keys is set. Since algorithm traverses everything, from the top of the tree to the bottom, we can't step into an arbitrary key pair merge, only observe and "jump-in" at the right time at the right key pair we need.

So, I'd answer, no. But solution is there.

I'm thinking about implementing the fourth argument in the callback. If it was a plain object, it could contain all the info about the **keys merged**: are they arrays or objects? what are their full paths (in [object-path](https://github.com/mariocasciaro/object-path) notation)? what are the names of the keys (so we don't need to slice and dice by full space)? All that could be used when meddling with the result. Even more so, in theory, you could even check, is it `key` at particular path, not affecting other, same-named keys at different paths.

What do you think?

**Comment by SnooHD** [comment]
Hello revelt, thanks for your reply.
I suppose that needing the `{key : value}` is an optional thing to start with, so i think that a 4th argument with all that extra information would be a great solution.

As far as i understand the code, i can't come up with a better alternative anyways..

**Comment by revelt** [comment]
Awesome! I'm planning to release tonight (fingers crossed), it's a no-brainer really since the data is there, we'll just pipe it to callback. 

Again, thank you for participating! I'll add you to the contributors list when this goes live 👍

**Comment by revelt** [comment]
done: https://github.com/codsen/object-merge-advanced#optscb-another-example-using-paths-of-the-keys-to-override-the-merge
